<a href="https://colab.research.google.com/github/rutu713/Machine-Learning/blob/main/Product_Review_Prediction_with_Multinominal_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [4]:
import numpy as np

In [16]:
import matplotlib.pyplot as plt

In [18]:
import seaborn as sns

In [19]:
from sklearn.feature_extraction.text import CountVectorizer


In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

In [9]:
df.head()


Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [14]:
df.shape

(23486, 10)

In [17]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [21]:
df[df['Review'] == ""] = np.nan
df['Review'].fillna("No review is given", inplace=True)
df.isna().sum()


Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [7]:
df['Review']


0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [9]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [11]:
x = df['Review']
y = df['Rating']
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, stratify=y, random_state=2529)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)


x_train = cv.fit_transform(x_train)  # Ensure it's a pandas Series

cv.get_feature_names_out()








array(['00 big', '00 fit', '00 fits', ..., 'zipper zip',
       'zippered pockets', 'zippers buttons'], dtype=object)

In [39]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:

x_test = cv.fit_transform(x_test)  # Ensure it's a pandas Series

cv.get_feature_names_out()




array(['00 24 xs', '00 aren', '00 aren size', ..., 'zone roomy looking',
       'zone style', 'zone style daughter'], dtype=object)

In [41]:
x_test.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, y_train)






MultinomialNB()

In [45]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

In [47]:
y_pred

array([2, 3, 5, ..., 4, 1, 1])

In [56]:
model.predict_proba(x_test)

array([[0.23233645, 0.58445508, 0.1147733 , 0.0512848 , 0.01715037],
       [0.12294881, 0.07301951, 0.75147082, 0.01024841, 0.04231245],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.02355456, 0.03500232, 0.03585817, 0.90206134, 0.00352362],
       [0.33707526, 0.32904614, 0.21413315, 0.11495564, 0.00478981],
       [0.70291792, 0.07159745, 0.16621238, 0.04826935, 0.0110029 ]])

In [58]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[  65   48   52   35   53]
 [ 149  116   48   62   95]
 [ 287  176  119  132  147]
 [ 555  309  201  196  262]
 [1342  776  585  536  700]]


In [60]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.03      0.26      0.05       253
           2       0.08      0.25      0.12       470
           3       0.12      0.14      0.13       861
           4       0.20      0.13      0.16      1523
           5       0.56      0.18      0.27      3939

    accuracy                           0.17      7046
   macro avg       0.20      0.19      0.15      7046
weighted avg       0.38      0.17      0.21      7046



In [62]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [63]:
df.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}}, inplace=True)

y=df['Rating']

x=df['Review']

In [65]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, stratify=y, random_state=2529)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [70]:

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)

x_train = cv.fit_transform(x_train)

x_test = cv.fit_transform(x_test)




In [72]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [78]:


# Step 5: Predict and evaluate
y_pred = model.predict(x_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Predictions shape:", y_pred.shape)



Accuracy: 0.5598921373829123
Predictions shape: (7046,)


In [80]:
y_pred

array([1, 0, 1, ..., 1, 0, 1])

In [82]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[ 601  982]
 [2119 3344]]


In [84]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.22      0.38      0.28      1583
           1       0.77      0.61      0.68      5463

    accuracy                           0.56      7046
   macro avg       0.50      0.50      0.48      7046
weighted avg       0.65      0.56      0.59      7046

